// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class AnswerEvaluation
{
    public int AnswerEvaluationId { get; set; }

    public int MilestoneQuestionAnsId { get; set; }

    public int TeamId { get; set; }

    public int EvaluatorId { get; set; }

    public int ReceiverId { get; set; }

    public decimal Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Lecturer Evaluator { get; set; }

    public virtual Student EvaluatorNavigation { get; set; }

    public virtual MilestoneQuestionAn MilestoneQuestionAns { get; set; }

    public virtual Student Receiver { get; set; }
}