// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CollabSphere.Domain.Entities;
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Models;

public partial class CardAssignment
{
    public int CardId { get; set; }

    public int StudentId { get; set; }

    public string StudentName { get; set; }

    public string Avatar { get; set; }

    public virtual Card Card { get; set; }
}