// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Card
{
    public int CardId { get; set; }

    public int ListId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string RiskLevel { get; set; }

    public float Position { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DueAt { get; set; }

    public bool? IsCompleted { get; set; }

    public virtual ICollection<CardAssignment> CardAssignments { get; set; } = new List<CardAssignment>();

    public virtual List List { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}