// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ChatConversation
{
    public int ConversationId { get; set; }

    public int? TeamId { get; set; }

    public string ConversationName { get; set; } = null!;

    public int? LatestMessageId { get; set; }

    public DateTime CreatedAt { get; set; }

    public int ClassId { get; set; }

    public virtual Class Class { get; set; } = null!;

    public virtual Team? Team { get; set; }

    public virtual ChatMessage? LatestMessage { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}