// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ChatConversation
{
    public int ConversationId { get; set; }

    public int TeamId { get; set; }

    public string ConversationName { get; set; }

    public int? LatestMessage { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual Team Team { get; set; }
}