// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class CheckpointSubmit
{
    public int CheckpointSubmitId { get; set; }

    public int CheckpointId { get; set; }

    public string SubmitFilePath { get; set; }

    public int ClassMemberId { get; set; }

    public DateTime SubmittedDate { get; set; }

    public virtual Checkpoint Checkpoint { get; set; }

    public virtual ICollection<CheckpointEvaluation> CheckpointEvaluations { get; set; } = new List<CheckpointEvaluation>();

    public virtual ClassMember ClassMember { get; set; }
}