// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class CheckpointAssignment
{
    public int CheckpointAssignmentId { get; set; }

    public int CheckpointId { get; set; }

    public int ClassMemberId { get; set; }

    public DateTime AssignedDate { get; set; }

    public virtual Checkpoint Checkpoint { get; set; }
    
    public virtual ClassMember ClassMember { get; set; }
}