// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Checkpoint
{
    public int CheckpointId { get; set; }

    public int TeamMilestoneId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Complexity { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly DueDate { get; set; }

    /// <summary>
    /// 0 - not done , 1 - done
    /// </summary>
    public int Status { get; set; }

    public virtual ICollection<CheckpointAssignment> CheckpointAssignments { get; set; } = new List<CheckpointAssignment>();

    public virtual ICollection<CheckpointFile> CheckpointFiles { get; set; } = new List<CheckpointFile>();

    public virtual TeamMilestone TeamMilestone { get; set; }
}