// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class CheckpointEvaluation
{
    public int CheckpointEvaluationId { get; set; }

    public int CheckpointSubmitId { get; set; }

    public int TeamId { get; set; }

    public int LecturerId { get; set; }

    public decimal? Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CheckpointId { get; set; }

    public virtual Checkpoint Checkpoint { get; set; }

    public virtual CheckpointSubmit CheckpointSubmit { get; set; }

    public virtual Lecturer Lecturer { get; set; }
}