// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ClassMember
{
    public int ClassMemberId { get; set; }

    public int StudentId { get; set; }

    public int? TeamId { get; set; }

    public int ClassId { get; set; }

    public string Fullname { get; set; }

    public int? TeamRole { get; set; }

    public bool IsGrouped { get; set; }

    public int Status { get; set; }

    public virtual ICollection<CheckpointAssignment> CheckpointAssignments { get; set; } = new List<CheckpointAssignment>();

    public virtual Class Class { get; set; }

    public virtual ICollection<MemberEvaluation> MemberEvaluationRaters { get; set; } = new List<MemberEvaluation>();

    public virtual ICollection<MemberEvaluation> MemberEvaluationReceivers { get; set; } = new List<MemberEvaluation>();

    public virtual ICollection<MilestoneQuestionAn> MilestoneQuestionAns { get; set; } = new List<MilestoneQuestionAn>();

    public virtual ICollection<MilestoneReturn> MilestoneReturns { get; set; } = new List<MilestoneReturn>();

    public virtual Student Student { get; set; }

    public virtual Team Team { get; set; }
}