// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ClassFile
{
    public int FileId { get; set; }

    public int ClassId { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; }

    public string Type { get; set; }

    public long FileSize { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ObjectKey { get; set; }

    public string FileUrl { get; set; }

    public DateTime UrlExpireTime { get; set; }

    public virtual Class Class { get; set; }

    public virtual User User { get; set; }
}