// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Class
{
    public int ClassId { get; set; }

    public string ClassName { get; set; }

    public int SubjectId { get; set; }

    public int SemesterId { get; set; }

    public int? LecturerId { get; set; }

    public string LecturerName { get; set; }

    public string EnrolKey { get; set; }

    public int? MemberCount { get; set; }

    public int? TeamCount { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ClassFile> ClassFiles { get; set; } = new List<ClassFile>();

    public virtual ICollection<ClassMember> ClassMembers { get; set; } = new List<ClassMember>();

    public virtual Lecturer Lecturer { get; set; }

    public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; } = new List<ProjectAssignment>();

    public virtual Semester Semester { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();

    public virtual ICollection<ChatConversation> ChatConversations { get; set; } = new List<ChatConversation>();
}