// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class DocumentState
{
    public int DocStateId { get; set; }

    public string RoomId { get; set; }

    public string UpdateData { get; set; }

    public DateTime CreatedTime { get; set; }
}