// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CollabSphere.Domain.Entities
{
    public class DocumentState
    {
        public int DocStateId { get; set; }

        public string RoomId { get; set; }

        public string UpdateData { get; set; }

        public DateTime CreatedTime { get; set; }
    }
}
