// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CollabSphere.Domain.Entities;
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class DocumentRoom
{
    public string RoomName { get; set; } = null!;

    public int TeamId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<DocumentState> DocumentStates { get; set; } = new List<DocumentState>();

    public virtual Team Team { get; set; } = null!;
}