// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CollabSphere.Domain.Entities;
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities
{
    public class DocumentState
    {
        public int DocStateId { get; set; }

        public string RoomName { get; set; }

        public int TeamId { get; set; }

        public string UpdateData { get; set; } = null!;

        public DateTime CreatedTime { get; set; }

        public int? UserId { get; set; }

        public virtual DocumentRoom DocumentRoom { get; set; }
    }
}
