// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class EvaluationDetail
{
    public int EvaluationDetailId { get; set; }

    public int TeamEvaluationId { get; set; }

    public int? SubjectGradeComponentId { get; set; }

    public decimal Percentage { get; set; }

    public decimal Score { get; set; }

    public string Comment { get; set; }

    public virtual TeamEvaluation TeamEvaluation { get; set; }
}