// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class GithubConnectionState
{
    public string StateToken { get; set; } = null!;

    public int ProjectId { get; set; }

    public int TeamId { get; set; }

    public int UserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Project Project { get; set; } = null!;

    public virtual Team Team { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}