// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Lecturer
{
    public int LecturerId { get; set; }

    public string Fullname { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public int? Yob { get; set; }

    public string AvatarImg { get; set; }

    public string School { get; set; }

    public string LecturerCode { get; set; }

    public string Major { get; set; }

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual User LecturerNavigation { get; set; }

    public virtual ICollection<MilestoneEvaluation> MilestoneEvaluations { get; set; } = new List<MilestoneEvaluation>();

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<TeamEvaluation> TeamEvaluations { get; set; } = new List<TeamEvaluation>();

    public virtual ICollection<TeamMemEvaluation> TeamMemEvaluations { get; set; } = new List<TeamMemEvaluation>();
}