// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class List
{
    public int ListId { get; set; }

    public int WorkspaceId { get; set; }

    public string Title { get; set; }
    public float Position { get; set; }

    public virtual ICollection<Card> Cards { get; set; } = new List<Card>();

    public virtual TeamWorkspace Workspace { get; set; } = null!;
}