// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Meeting
{
    public int MeetingId { get; set; }

    public int TeamId { get; set; }

    public string Title { get; set; } = null!;

    public string? Description { get; set; }

    public int CreatedBy { get; set; }

    public DateTime ScheduleTime { get; set; }

    public DateTime CreatedAt { get; set; }

    public int Status { get; set; }

    public string? CreatorName { get; set; }

    public string? MeetingUrl { get; set; }

    public string? RecordUrl { get; set; }
    public virtual Team Team { get; set; } = null!;
}