// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MemberEvaluation
{
    public int MemberEvaluationId { get; set; }

    public int TeamId { get; set; }

    public int RaterId { get; set; }

    public int ReceiverId { get; set; }

    public decimal Score { get; set; }

    public string Comment { get; set; }

    public virtual ClassMember Rater { get; set; }

    public virtual ClassMember Receiver { get; set; }

    public virtual Team Team { get; set; }
}