// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MessageRecipient
{
    public int MessageRecipientId { get; set; }

    public int MessageId { get; set; }

    public int ReceiverId { get; set; }

    public bool IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public virtual ChatMessage Message { get; set; }

    public virtual User Receiver { get; set; }
}