// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MilestoneQuestionAn
{
    public int MilestoneQuestionAnsId { get; set; }

    public int MilestoneQuestionId { get; set; }

    public int TeamId { get; set; }

    public int ClassMemberId { get; set; }

    public string Answer { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<AnswerEvaluation> AnswerEvaluations { get; set; } = new List<AnswerEvaluation>();

    public virtual ClassMember ClassMember { get; set; }

    public virtual MilestoneQuestion MilestoneQuestion { get; set; }
}