// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MilestoneReturn
{
    public int MileReturnId { get; set; }

    public int TeamMilestoneId { get; set; }

    public int UserId { get; set; }

    public string FileName { get; set; } = null!;

    public string Type { get; set; } = null!;

    public long FileSize { get; set; }

    public DateTime SubmitedDate { get; set; }

    public string ObjectKey { get; set; } = null!;

    public string FileUrl { get; set; } = null!;

    public DateTime UrlExpireTime { get; set; }

    public virtual TeamMilestone TeamMilestone { get; set; } = null!;

    public virtual User User { get; set; } = null!;
}