// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MilestoneQuestion
{
    public int MilestoneQuestionId { get; set; }

    public int TeamMilestoneId { get; set; }

    public int TeamId { get; set; }

    public string Question { get; set; }

    public int? AnswerCount { get; set; }

    public DateTime CreatedTime { get; set; }

    public virtual ICollection<MilestoneQuestionAn> MilestoneQuestionAns { get; set; } = new List<MilestoneQuestionAn>();

    public virtual TeamMilestone TeamMilestone { get; set; }
}