// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MilestoneReturn
{
    public int MileReturnId { get; set; }

    public int TeamMilestoneId { get; set; }

    public int ClassMemberId { get; set; }

    public string FilePath { get; set; }

    public string Type { get; set; }

    public DateTime SubmitedDate { get; set; }

    public virtual ClassMember ClassMember { get; set; }

    public virtual TeamMilestone TeamMilestone { get; set; }
}