// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class MilestoneEvaluation
{
    public int MilestoneId { get; set; }

    public int LecturerId { get; set; }

    public int TeamId { get; set; }

    public decimal? Score { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Lecturer Lecturer { get; set; }

    public virtual TeamMilestone Milestone { get; set; }

    public virtual Team Team { get; set; }
}