// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string Title { get; set; }

    public string Content { get; set; }

    public string NotificationType { get; set; }

    public int? ReferenceId { get; set; }

    public string ReferenceType { get; set; }

    public string Link { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<NotificationRecipient> NotificationRecipients { get; set; } = new List<NotificationRecipient>();
}