// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class NotificationRecipient
{
    public int NotificationRecipientId { get; set; }

    public int NotificationId { get; set; }

    public int ReceiverId { get; set; }

    public bool IsRead { get; set; }

    public DateTime? ReadAt { get; set; }

    public virtual Notification Notification { get; set; }

    public virtual User Receiver { get; set; }
}