// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Objective
{
    public int ObjectiveId { get; set; }

    public string Description { get; set; }

    public string Priority { get; set; }

    public int ProjectId { get; set; }

    public virtual ICollection<ObjectiveMilestone> ObjectiveMilestones { get; set; } = new List<ObjectiveMilestone>();

    public virtual Project Project { get; set; }
}