// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ObjectiveMilestone
{
    public int ObjectiveMilestoneId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int ObjectiveId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public virtual Objective Objective { get; set; }

    public virtual ICollection<TeamMilestone> TeamMilestones { get; set; } = new List<TeamMilestone>();
}