// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class PrAnalysis
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int TeamId { get; set; }

    public long RepositoryId { get; set; }

    public int PrNumber { get; set; }

    public string? PrTitle { get; set; }

    public string? PrAuthorGithubUsername { get; set; }

    public string? PrUrl { get; set; }

    public string? PrState { get; set; }

    public DateTime? PrCreatedAt { get; set; }

    public int? AiOverallScore { get; set; }

    public string? AiSummary { get; set; }

    public string? AiDetailedFeedback { get; set; }

    public int? AiBugCount { get; set; }

    public int? AiSecurityIssueCount { get; set; }

    public int? AiSuggestionCount { get; set; }

    public DateTime? AnalyzedAt { get; set; }

    public virtual Project Project { get; set; } = null!;

    public virtual Team Team { get; set; } = null!;
}