// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ProjectInstallation
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public long GithubInstallationId { get; set; }

    public int InstalledByUserId { get; set; }

    public DateTime? InstalledAt { get; set; }

    public virtual User InstalledByUser { get; set; } = null!;

    public virtual Project Project { get; set; } = null!;
}