// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ProjectRepository
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public long GithubRepoId { get; set; }

    public string RepositoryName { get; set; } = null!;

    public string RepositoryUrl { get; set; } = null!;

    public long? WebhookId { get; set; }

    public int ConnectedByUserId { get; set; }

    public DateTime? ConnectedAt { get; set; }

    public virtual User ConnectedByUser { get; set; } = null!;

    public virtual Project Project { get; set; } = null!;
}