// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ProjectRepoMapping
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public int TeamId { get; set; }

    public long GithubInstallationId { get; set; }

    public string RepositoryFullName { get; set; } = null!;

    public long RepositoryId { get; set; }

    public int InstalledByUserid { get; set; }

    public DateTime? InstalledAt { get; set; }

    public virtual Project Project { get; set; } = null!;

    public virtual Team Team { get; set; } = null!;
    public virtual User InstalledByUser { get; set; } = null!;
}