// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Project
{
    public int ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string Description { get; set; }

    public int LecturerId { get; set; }

    public int SubjectId { get; set; }

    /// <summary>
    /// 0 - Pending,
    /// 1 - Approved,
    /// 2 - Denied
    /// </summary>
    public int Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public int UpdatedBy { get; set; }

    public virtual Lecturer Lecturer { get; set; }

    public virtual ICollection<Objective> Objectives { get; set; } = new List<Objective>();

    public virtual ICollection<ProjectAssignment> ProjectAssignments { get; set; } = new List<ProjectAssignment>();

    public virtual ICollection<ProjectInstallation> ProjectInstallations { get; set; } = new List<ProjectInstallation>();

    public virtual Subject Subject { get; set; }
}