// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class ProjectAssignment
{
    public int ProjectAssignmentId { get; set; }

    public int ProjectId { get; set; }

    public int ClassId { get; set; }

    public DateTime AssignedDate { get; set; }

    public int Status { get; set; }

    public virtual Class Class { get; set; }

    public virtual Project Project { get; set; }

    public virtual ICollection<Team> Teams { get; set; } = new List<Team>();
}