// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CollabSphere.Domain.Entities
{
    public partial class Semester
    {
        public int SemesterId { get; set; }

        public string SemesterName { get; set; }

        public DateOnly StartDate { get; set; }

        public DateOnly EndDate { get; set; }

        public virtual ICollection<Class> Classes { get; set; } = new List<Class>();
    }
}
