// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Models;

public partial class Shape
{
    public string ShapeId { get; set; }

    public int PageId { get; set; }

    public int DrawerId { get; set; }

    public string JsonData { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual WhiteboardPage Page { get; set; }
}