// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CollabSphere.Domain.Models;
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Student
{
    public int StudentId { get; set; }

    public string Fullname { get; set; }

    public string Address { get; set; }

    public string PhoneNumber { get; set; }

    public int? Yob { get; set; }

    public string AvatarImg { get; set; }

    public string School { get; set; }

    public string StudentCode { get; set; }

    public string Major { get; set; }

    public virtual ICollection<AnswerEvaluation> AnswerEvaluationEvaluatorNavigations { get; set; } = new List<AnswerEvaluation>();

    public virtual ICollection<AnswerEvaluation> AnswerEvaluationReceivers { get; set; } = new List<AnswerEvaluation>();

    public virtual ICollection<CardAssignment> CardAssignments { get; set; } = new List<CardAssignment>();

    public virtual ICollection<ClassMember> ClassMembers { get; set; } = new List<ClassMember>();

    public virtual User StudentNavigation { get; set; }
}