// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class SubjectGradeComponent
{
    public int SubjectGradeComponentId { get; set; }

    public int SubjectId { get; set; }

    public int SyllabusId { get; set; }

    public string ComponentName { get; set; }

    public decimal? ReferencePercentage { get; set; }

    public virtual SubjectSyllabus Syllabus { get; set; }
}