// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class SubjectOutcome
{
    public int SubjectOutcomeId { get; set; }

    public int SyllabusId { get; set; }

    public string OutcomeDetail { get; set; }

    public virtual SubjectSyllabus Syllabus { get; set; }

    public virtual ICollection<SyllabusMilestone> SyllabusMilestones { get; set; } = new List<SyllabusMilestone>();
}