// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Subject
{
    public int SubjectId { get; set; }

    public string SubjectName { get; set; }

    public string SubjectCode { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual ICollection<SubjectSyllabus> SubjectSyllabi { get; set; } = new List<SubjectSyllabus>();
}