// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class SubjectSyllabus
{
    public int SyllabusId { get; set; }

    public string SyllabusName { get; set; }

    public string Description { get; set; }

    public string SubjectCode { get; set; }

    public int SubjectId { get; set; }

    public int? NoCredit { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsActive { get; set; }

    public virtual Subject Subject { get; set; }

    public virtual ICollection<SubjectGradeComponent> SubjectGradeComponents { get; set; } = new List<SubjectGradeComponent>();

    public virtual ICollection<SubjectOutcome> SubjectOutcomes { get; set; } = new List<SubjectOutcome>();
}