// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Models;

public partial class SubTask
{
    public int SubTaskId { get; set; }

    public string SubTaskTitle { get; set; }

    public int Order { get; set; }

    public bool? IsDone { get; set; }

    public int TaskId { get; set; }

    public virtual Task Task { get; set; }
}