// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class SyllabusMilestone
{
    public int SyllabusMilestoneId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly StarDate { get; set; }

    public DateOnly EndDate { get; set; }

    public int SyllabusId { get; set; }

    public int SubjectOutcomeId { get; set; }

    public virtual SubjectOutcome SubjectOutcome { get; set; }

    public virtual SubjectSyllabus Syllabus { get; set; }

    public virtual ICollection<TeamMilestone> TeamMilestones { get; set; } = new List<TeamMilestone>();
}