// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Task
{
    public int TaskId { get; set; }

    public string TaskTitle { get; set; }

    public int CardId { get; set; }

    public int Order { get; set; }

    public virtual Card Card { get; set; }

    public virtual ICollection<SubTask> SubTasks { get; set; } = new List<SubTask>();
}