// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class TeamFile
{
    public int FileId { get; set; }

    public int TeamId { get; set; }

    public string FilePath { get; set; }

    public string Type { get; set; }

    public virtual Team Team { get; set; }
}