// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class TeamMemEvaluation
{
    public int TeamMemEvaluationId { get; set; }

    public int TeamId { get; set; }

    public int? LecturerId { get; set; }

    public int ClassMemberId { get; set; }

    public decimal? Score { get; set; }

    public virtual ClassMember ClassMember { get; set; } = null!;

    public virtual Lecturer? Lecturer { get; set; }

    public virtual Team Team { get; set; } = null!;
}