// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Models;

public partial class TeamWhiteboard
{
    public int WhiteboardId { get; set; }

    public int TeamId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<WhiteboardPage> WhiteboardPages { get; set; } = new List<WhiteboardPage>();
}