// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class TeamMilestone
{
    public int TeamMilestoneId { get; set; }

    public int? SyllabusMilestoneId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int TeamId { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public float? Progress { get; set; }

    /// <summary>
    /// 0 - not done , 1 - done
    /// </summary>
    public int Status { get; set; }

    public virtual ICollection<Checkpoint> Checkpoints { get; set; } = new List<Checkpoint>();

    public virtual MilestoneEvaluation MilestoneEvaluation { get; set; }

    public virtual ICollection<MilestoneFile> MilestoneFiles { get; set; } = new List<MilestoneFile>();

    public virtual ICollection<MilestoneQuestion> MilestoneQuestions { get; set; } = new List<MilestoneQuestion>();

    public virtual ICollection<MilestoneReturn> MilestoneReturns { get; set; } = new List<MilestoneReturn>();

    public virtual SyllabusMilestone SyllabusMilestone { get; set; }

    public virtual Team Team { get; set; }
}