// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class TeamEvaluation
{
    public int TeamEvaluationId { get; set; }

    public int TeamId { get; set; }

    public int LecturerId { get; set; }

    public decimal? FinalGrade { get; set; }

    public string Comment { get; set; }

    public virtual ICollection<EvaluationDetail> EvaluationDetails { get; set; } = new List<EvaluationDetail>();

    public virtual Lecturer Lecturer { get; set; }

    public virtual Team Team { get; set; }
}