// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class Team
{
    public int TeamId { get; set; }

    public string TeamName { get; set; }

    public string TeamImage { get; set; }

    public string EnrolKey { get; set; }

    public string Description { get; set; }

    public int LeaderId { get; set; }

    public int ClassId { get; set; }

    public int? ProjectAssignmentId { get; set; }

    public int LecturerId { get; set; }

    public string LecturerName { get; set; }

    public DateOnly CreatedDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public float? Progress { get; set; }

    public int Status { get; set; }

    public virtual ICollection<ChatConversation> ChatConversations { get; set; } = new List<ChatConversation>();

    public virtual Class Class { get; set; }

    public virtual ICollection<ClassMember> ClassMembers { get; set; } = new List<ClassMember>();

    public virtual ICollection<Meeting> Meetings { get; set; } = new List<Meeting>();

    public virtual ICollection<MemberEvaluation> MemberEvaluations { get; set; } = new List<MemberEvaluation>();

    public virtual ProjectAssignment ProjectAssignment { get; set; }

    public virtual ICollection<TeamEvaluation> TeamEvaluations { get; set; } = new List<TeamEvaluation>();

    public virtual ICollection<TeamFile> TeamFiles { get; set; } = new List<TeamFile>();

    public virtual ICollection<TeamMilestone> TeamMilestones { get; set; } = new List<TeamMilestone>();
}