// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Entities;

public partial class TeamWorkspace
{
    public int WorkspaceId { get; set; }

    public int TeamId { get; set; }

    public string Title { get; set; }

    public DateOnly CreatedAt { get; set; }

    public virtual ICollection<List> Lists { get; set; } = new List<List>();
}