// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CollabSphere.Domain.Models;

public partial class WhiteboardPage
{
    public int PageId { get; set; }

    public int? WhiteboardId { get; set; }

    public string PageTitle { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsActivate { get; set; }

    public virtual ICollection<Shape> Shapes { get; set; } = new List<Shape>();

    public virtual TeamWhiteboard Whiteboard { get; set; }
}